### ISSUE TITLE
[Bug]: old version in registry

### ISSUE THREAD

**Issue by condemil** [aspect-build/rules_esbuild#140] opened 2023-03-14 10:54 UTC
### What happened?

I see at https://registry.bazel.build/modules/aspect_rules_esbuild that the latest version is 0.14.0, but at https://github.com/aspect-build/rules_esbuild/releases I see newer version 0.14.2

### Version

N/A

**Comment by gregmagolan** [comment] 2023-03-14 16:11
BCR has Windows CI and there was a Windows issue at HEAD caused by changes in the latest esbuild releases that was causing failures on the central registry CI so the latest releases couldn't be landed there.

We fixed in the last few days. I'll cut a 1.14.3 release and should be green on BCR now.

**Comment by gregmagolan** [comment] 2023-03-14 16:23
https://github.com/bazelbuild/bazel-central-registry/pull/515 looks all good

**Closed** 2023-03-14 16:24 UTC
Labels: bug
